services:
  - type: web
    name: admin-user-api
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
